import{a as L,S as w,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const S="49321124-d9248d4be3ea0dc21aad93268",v="https://pixabay.com/api/";let c=1;async function u(s,t=!1){t&&(c=1);try{const r=await L.get(v,{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:c}});return r.data.hits.length>0&&(c+=1),r.data.hits}catch(r){return console.error("Error fetching images:",r),[]}}async function m(s){const t=document.querySelector(".gallery");try{t.innerHTML="",t.innerHTML=s.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}" class="gallery-link">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy">
      </a>
      <div class="info">
        <p><span class="matter">Likes</span> ${o.likes}</p>
        <p><span class="matter">Views</span> ${o.views}</p>
        <p><span class="matter">Comments</span> ${o.comments}</p>
        <p><span class="matter">Downloads</span> ${o.downloads}</p>
      </div>
    </li>
  `).join(""),new w(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}catch(r){console.error("Error rendering gallery:",r)}}const p=document.querySelector(".form"),d=document.querySelector(".loader"),f=p.querySelector("input[name='search-text']"),b=document.querySelector(".gallery"),i=document.querySelector(".btn");d.classList.add("hidden");i.classList.add("hidden");function g(){d.classList.remove("hidden")}function y(){d.classList.add("hidden")}function q(){i.classList.remove("hidden")}function h(){i.classList.add("hidden")}p.addEventListener("submit",async s=>{s.preventDefault();const t=f.value.trim();if(!t){n.error({message:"Please enter a search query!"});return}b.innerHTML="",h(),g();try{const r=await u(t,!0);r.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(m(r),q())}catch{n.error({message:"Something went wrong. Please try again later."})}finally{y()}});i.addEventListener("click",async()=>{g();try{const s=await u(f.value.trim());s.length===0?(n.info({message:"No more images to load."}),h()):m(s,!0)}catch{n.error({message:"Something went wrong. Please try again later."})}finally{y()}});
//# sourceMappingURL=index.js.map
