import{a as b,S,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const q="49321124-d9248d4be3ea0dc21aad93268",P="https://pixabay.com/api/";let d=1,u=0;async function p(a,t=!1){t&&(d=1,u=0);try{const r=await b.get(P,{params:{key:q,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:d}});return t&&(u=r.data.totalHits),r.data.hits.length>0&&(d+=1),{images:r.data.hits,totalHits:u}}catch(r){return console.error("Error fetching images:",r),{images:[],totalHits:0}}}async function g(a){const t=document.querySelector(".gallery");try{t.innerHTML="",t.innerHTML=a.map(s=>`
    <li class="gallery-item">
      <a href="${s.largeImageURL}" class="gallery-link">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy">
      </a>
      <div class="info">
        <p><span class="matter">Likes</span> ${s.likes}</p>
        <p><span class="matter">Views</span> ${s.views}</p>
        <p><span class="matter">Comments</span> ${s.comments}</p>
        <p><span class="matter">Downloads</span> ${s.downloads}</p>
      </div>
    </li>
  `).join(""),new S(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}catch(r){console.error("Error rendering gallery:",r)}}const h=document.querySelector(".form"),m=document.querySelector(".loader"),y=h.querySelector("input[name='search-text']"),H=document.querySelector(".gallery"),l=document.querySelector(".btn");let f=0,i=0;m.classList.add("hidden");l.classList.add("hidden");function L(){m.classList.remove("hidden")}function w(){m.classList.add("hidden")}function E(){l.classList.remove("hidden")}function v(){l.classList.add("hidden")}h.addEventListener("submit",async a=>{a.preventDefault();const t=y.value.trim();if(!t){n.error({message:"Please enter a search query!"});return}H.innerHTML="",v(),L();try{const r=await p(t,!0);if(!r||!r.images)throw new Error("Invalid response from API");const{images:s,totalHits:e}=r;f=e,i=s.length,s.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(g(s),i<f&&E())}catch{n.error({message:"Something went wrong. Please try again later."})}finally{w()}});l.addEventListener("click",async()=>{L();try{const a=await p(y.value.trim());if(!a||!a.images)throw new Error("Invalid response from API");const{images:t}=a;i+=t.length,t.length===0||i>=f?(n.info({message:"We're sorry, but you've reached the end of search results."}),v()):g(t,!0)}catch{n.error({message:"Something went wrong. Please try again later."})}finally{w()}});
//# sourceMappingURL=index.js.map
