import{a as b,S as q,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function t(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(r){if(r.ep)return;r.ep=!0;const a=t(r);fetch(r.href,a)}})();const P="49321124-d9248d4be3ea0dc21aad93268",E="https://pixabay.com/api/";async function h(o,e){try{const t=await b.get(E,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}});return{images:t.data.hits||[],totalHits:t.data.totalHits||0}}catch(t){return console.error("Error fetching images:",t),{images:[],totalHits:0}}}const p=document.querySelector(".gallery");let m=null;function y(o,e=!1){try{e||(p.innerHTML="");const t=o.map(s=>`
      <li class="gallery-item">
        <a href="${s.largeImageURL}" class="gallery-link">
          <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy">
        </a>
        <div class="info">
          <p><span class="matter">Likes:</span> ${s.likes}</p>
          <p><span class="matter">Views:</span> ${s.views}</p>
          <p><span class="matter">Comments:</span> ${s.comments}</p>
          <p><span class="matter">Downloads:</span> ${s.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",t),m?m.refresh():m=new q(".gallery a",{captionsData:"alt",captionDelay:250})}catch(t){console.error("Error rendering gallery:",t)}}const L=document.querySelector(".form"),g=document.querySelector(".loader"),H=L.querySelector("input[name='search-text']"),I=document.querySelector(".gallery"),d=document.querySelector(".btn");let f=0,i=0,l="",c=1;g.classList.add("hidden");d.classList.add("hidden");function w(){g.classList.remove("hidden")}function v(){g.classList.add("hidden")}function $(){d.classList.remove("hidden")}function S(){d.classList.add("hidden")}function M(){var e;const o=((e=document.querySelector(".gallery-item"))==null?void 0:e.getBoundingClientRect().height)||0;window.scrollBy({top:o*2,behavior:"smooth"})}L.addEventListener("submit",async o=>{o.preventDefault();const e=H.value.trim();if(!e){n.error({message:"Please enter a search query!"});return}e!==l&&(l=e,i=0,c=1),I.innerHTML="",S(),w();try{const t=await h(l,c);if(!t||!t.images)throw new Error("Invalid response from API");const s=t.images;if(f=t.totalHits,i=s.length,s.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}else y(s),i<f&&$()}catch{n.error({message:"Something went wrong. Please try again later."})}finally{v()}});d.addEventListener("click",async()=>{w(),c+=1;try{const o=await h(l,c);if(!o||!o.images)throw new Error("Invalid response from API");const e=o.images;i+=e.length,e.length===0||i>=f?(n.info({message:"We're sorry, but you've reached the end of search results."}),S()):(y(e,!0),M())}catch{n.error({message:"Something went wrong. Please try again later."})}finally{v()}});
//# sourceMappingURL=index.js.map
